app.controller('ProjectsController', function ($animate,$scope) {
	$scope.data=[
	{"name":"Evil Hangperson Game",
	"language":"Java/Swing GUI",
	"image":"images/EvilHang.jpg",
	"description":"This game incorporates a dictionary file that contains more than 10000 entries, and the user shall guess which letters are contained in the answer word. The goal is to make the user lose whenever possible. Thus, each time the user makes a guess, all words containing that letter are eliminated from the list. The user only wins when there is one pontential answer.",
	"link":"https://github.com/shalxu/Projects/tree/master/EvilHangPerson"
	},
	{"name":"Mock Maplestory Game",
	"language":"Java/Processing IDE",
	"image":"images/maplestory.jpg",
	"description":"This game imitates layout of the game MapleStory by Nexon, and allows the users to attack randomly generated mushroom monsters with magic bolts. The player shall collect enough coins from killed monsters to win the game.",
	"link":"https://github.com/shalxu/Projects/tree/master/skecth_34_maplestory"
	},
	{"name":"Mock Plant vs Zombies Game",
	"language":"Java/Swing GUI",
	"image":"images/PlantVsZombies.jpg",
	"description":"This strategy game imitates layout of the game Plant vs Zombies by PopCap. The user should carefully choose where to plant which plants, and defend against destructive zombies.",
	"link":"https://github.com/shalxu/Projects/tree/master/PvZ%20Project"
	},
	{"name":"Colorful Galaga",
	"language":"Java/Processing IDE",
	"image":"images/Galaga.jpg",
	"description":"This game imitates layout of the traditional Galaga game. Travelling in a universe of stars, the user shall control a spaceship to dolge attacks, and launch missles to attack enemy spaceships. All designs are completed with a basic Java geometrical drawing library, and enemy spaceships have routes generated by mathematical algorithms.",
	"link":"https://github.com/shalxu/Projects/tree/master/Galaga"
	},
	{"name":"Yoga Quizzer",
	"language":"HTML/CSS/Javascript/PHP/XAMPP",
	"image":"images/yoga.jpg",
	"description":"This is a Single-Page Web Application that quizzes students about yoga positions. There are two modes (multiple choice and right/wrong). Each student is shown a image, and prompted to choose among buttons of choices. User information and previous scores are stored locally using cookies. Questions are randomly generated based on existing question-answer pairs" ,
	"link":"https://github.com/shalxu/Projects/tree/master/yoga.php"
	},
	{"name":"Shop Love + Light",
	"language":"Shopify",
	"image":"images/boutique.jpg",
	"description":"The Shopify website was created and designed after collecting requirements and design specifications from the customer. The goal was to set up a vibrant, sleek E-commerce platform, and allows users to easily browse through products and have a clear perception of the company image.",
	"link":"https://loveandlight.boutique"
	},
	];
	$scope.updateModal=function(index){
		var temp=$scope.data[index];
		console.log($scope.data);
		document.getElementById("head").innerHTML =temp["name"];
		document.getElementById("description").innerHTML =temp["description"];
		document.getElementById("image").src =temp["image"];
	}

});
